const experience =[
    {
        id: 5,
        title :"Full Stack Intern",
        institute: "Appweave Labs",
        instituteURL :"https://appweave.tech/",
        skill:["React js","js","npm"],
        learn :["localstorage","text-filter","search filter"],
        imgURL :"./img/Appweave offer letter.jpg",
        certification:"https://drive.google.com/file/d/1wpLRGQ9M-1qmGhDT60iFb1anqQJgA85e/view?usp=sharing",
        projectTitle :"Appweave Shopy",
        projectLink :"https://fthabhishek-pandey.github.io/Appweave-Shop/",
        desp:"",
     },
    {
        id: 4,
        title :"IT Intern Trainee",
        institute: "Collegites - BLACK R Enterprises",
        instituteURL :"https://www.linkedin.com/company/sdcrecabn/",
        skill:["Tailwind","CSS","HTML"],
        learn :"Pop-up",
        imgURL :"img/collegites-certificate_page-0001.jpg",
        certification:"https://drive.google.com/file/d/11PwfyAju8fz-ViToziR6bD234lUih1-R/view?usp=sharing",
        projectTitle :"",
        projectLink :"",
        desp:" • I learn industry ready html , CSS, Tailwind CSS, Sass, JavaScript , git and GitHub etc. developing tools.<br>• Working with a team, I learned how to work in team for creating a software product and also take a look of workplace culture.",
     },
    {
        id: 3,
        title :"Teaching Assistent",
        institute: "Software Development Club",
        instituteURL :"https://www.linkedin.com/company/sdcrecabn/",
        skill:"",
        learn :"",
        imgURL :"img/pexels-alex-green-5699479.jpg",
        certification:"",
        projectTitle :"",
        projectLink :"",
        desp:"• I assist students in debugging code related to Data Structures and Algorithms, ensuring the efficiency of their programs. • I achieved Ranked 1st in college coding competition in 2023 organised by Software development club.",
     },
    {
        id: 2,
        title :"Mentor As Physics Teacher",
        institute: "Koshish",
        instituteURL :"https://www.linkedin.com/company/koshish-institute-of-education/",
        skill:"",
        learn :"",
        imgURL :"./img/koshishClass12.jpg",
        certification:"",
        projectTitle :"",
        projectLink :"",
        desp:"• I mentored the class 12th student as a Physics Teacher in 2023-24 section.<br> • Currently ,I served as managerial team member to monitoring class.",
     },
     {
        id: 1,
        title :"PW Campus Ambassador",
        institute: "Physics Wallah",
        instituteURL :"",
        skill:"Leadership",
        learn :"",
        imgURL :"img/CAP 7.O Certificates-35 (1)_page-0001.jpg",
        certification:"https://drive.google.com/file/d/1La_01z408_X7PQo1y5-bfv84WNVRaWo7/view?usp=sharing",
        projectTitle :"",
        projectLink :"",
        desp:" As a Campus Ambassador, I connected peers with opportunities, organized events, and represented the brand, fostering a vibrant community and amplifying brand awareness.",
     },
]
function experienceDataf(){
    return experience;
}
export default experienceDataf;